//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aprendendoGenyx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionalidade
    {
        public funcionalidade()
        {
            this.funcionalidade1 = new HashSet<funcionalidade>();
            this.funcionalidade_permissao = new HashSet<funcionalidade_permissao>();
            this.grupo = new HashSet<grupo>();
            this.permissao = new HashSet<permissao>();
        }
    
        public int funcionalidade_id { get; set; }
        public Nullable<int> funcionalidade_pai_id { get; set; }
        public string nome { get; set; }
        public string controller { get; set; }
        public byte ordem { get; set; }
        public byte show_menu { get; set; }
        public byte deleted { get; set; }
    
        public virtual ICollection<funcionalidade> funcionalidade1 { get; set; }
        public virtual funcionalidade funcionalidade2 { get; set; }
        public virtual ICollection<funcionalidade_permissao> funcionalidade_permissao { get; set; }
        public virtual ICollection<grupo> grupo { get; set; }
        public virtual ICollection<permissao> permissao { get; set; }
    }
}
